### ISSUE TITLE
[Feature request] 添加office文档共同协作功能

### ISSUE THREAD

**Issue by Gabrielvon** [NovelResearchInvestment/nextcloud-server#3]

**Comment by Gabrielvon** [comment]
Office Online基本功能缺失，如筛选和排序等 

@yuuolo 回复下现在尝试方案

**Comment by Gabrielvon** [comment]
正在MS Office Online, Onlyoffice, Collabora Online之间选择。

- MS Office Online，部署后缺少功能，如筛选排序

- Onlyoffice, 可道云正在使用，使用过程中，excel编辑时，一些值会乱跑，无法对应。暂时不确定是以下哪个原因

     - 用户使用习惯问题
     - 服务器处理不够及时
     - 软件服务自身设计逻辑有问题

- Collabora Online, 基于libre office, 拓展性更高

**Comment by yuuolo** [comment]
最终部署了onlyoffice 7.2，已经添加中文字体。

**Comment by yuuolo** [comment]
![Uploading WechatIMG400.jpeg…]()

**Comment by yuuolo** [comment]
[](url)
