### ISSUE TITLE
[Bug] onlyoffice插件的doc文件，插入公式显示中英文字乱码

### ISSUE THREAD

**Issue by Gabrielvon** [NovelResearchInvestment/nextcloud-server#6]
如下图

![Image](https://github.com/NovelResearchInvestment/nextcloud-server/assets/8952869/462dfaec-b35a-4689-8efc-278027626a93)

**Comment by yuuolo** [comment]
![image](https://github.com/NovelResearchInvestment/nextcloud-server/assets/12983493/b5b72f49-b302-4ead-b29d-5ec25068230e)

**Comment by Gabrielvon** [comment]
> ![image](https://user-images.githubusercontent.com/12983493/241615913-b5b72f49-b302-4ead-b29d-5ec25068230e.png)

请说明下出现问题的原因，已经解决方案。
